name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches:
      - production

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          server-dir: /public_html/ # 👈 FTP server directory only the path access given to account
          state-name: .ftp-deploy-sync-state.json   # 👈 keeps track of last deploy